### ISSUE TITLE
test with different types of inputs, v2

### ISSUE THREAD

**Issue by amirhpd** [amirhpd/AST-Project-2018#1]
code should be tested with different kinds of inputs, as mentioned in first part of :
https://github.com/deebuls/ast-2018/blob/master/project-2018/requirement_update_1.md

**Comment by sidra718** [comment]
Modified code was tested again using the same inputs and throws success. However, it should not be successful because the development code is written in a way where it is not possible to catch errors. For example, selector function selects the highest precision but does not consider whether items being compared are the same items.
[issues_v2.txt](https://github.com/amirhossein-p/AST-Project-2018/files/2657360/issues_v2.txt)

**Comment by amirhpd** [comment]
Function getOutput added to the main code, so it is possible to check the mentioned part of procedure by test code.

**Comment by sidra718** [comment]
getOutput function tested with errors. 
Error is when the lists are of different sizes.
[issue2_v2.txt](https://github.com/amirhossein-p/AST-Project-2018/files/2657392/issue2_v2.txt)

**Comment by amirhpd** [comment]
GetOutput function updated to solve issues. Now getOutput function calls selector function. So no need to test selector function individually.

**Comment by sidra718** [comment]
GetOutput function tested giving successful results. The program compares precision between two similar items and also handles lists with different sizes.
[issue3_v2.txt](https://github.com/amirhossein-p/AST-Project-2018/files/2657490/issue3_v2.txt)
